# Generated by Django 4.2.5 on 2023-09-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0003_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='partners',
            field=models.ManyToManyField(blank=True, to='phc.partners'),
        ),
    ]
