# Generated by Django 4.2.5 on 2023-09-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0004_subcounty_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounty',
            name='partners',
        ),
        migrations.AddField(
            model_name='subcounty',
            name='partners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phc.partners'),
        ),
    ]
