# Generated by Django 4.2.5 on 2023-09-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0005_remove_subcounty_partners_subcounty_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='partners',
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='phc.question')),
                ('subcounty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phc.subcounty')),
            ],
        ),
        migrations.AddField(
            model_name='subcounty',
            name='partners',
            field=models.ManyToManyField(blank=True, to='phc.partners'),
        ),
    ]
