# Generated by Django 4.2.5 on 2023-09-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0006_question_remove_subcounty_partners_questionnaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='subcounty',
        ),
        migrations.AddField(
            model_name='subcounty',
            name='indicators',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phc.questionnaire'),
        ),
    ]
