# Generated by Django 4.2.5 on 2023-09-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0007_rename_answer_question_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
