# Generated by Django 4.2.5 on 2023-09-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0010_remove_questionnaire_step_question_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Step',
            new_name='step',
        ),
    ]
