# Generated by Django 4.2.5 on 2023-09-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0011_rename_step_question_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='indicators',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phc.question'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phc.subcounty'),
        ),
    ]
