# Generated by Django 4.2.5 on 2023-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0012_questionresponse_remove_question_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chmt_meeting', models.BooleanField(default=False, verbose_name='Has CHMT meeting taken place?')),
                ('schmt_hf_staff_meeting', models.BooleanField(default=False, verbose_name='Has the SCHMT & HF staff meeting taken place?')),
            ],
        ),
        migrations.CreateModel(
            name='Step2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_facility_assessments', models.BooleanField(default=False, verbose_name='Have Health Facility assessments taken place – using the 6 building blocks?')),
                ('client_exit_surveys', models.BooleanField(default=False, verbose_name='Have client exit surveys taken place?')),
                ('chu_functionality_assessments', models.BooleanField(default=False, verbose_name='Have the CHU functionality assessments taken place?')),
            ],
        ),
        migrations.CreateModel(
            name='Step3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_of_hubs_and_spokes', models.BooleanField(default=False, verbose_name='Has the mapping of the hubs and spokes taken place (including link to CHUs)?')),
                ('training_of_mdts', models.BooleanField(default=False, verbose_name='Has the training of multi-disciplinary teams (MDTs) taken place?')),
                ('performance_indicators_customized', models.BooleanField(default=False, verbose_name='Have the performance indicators been customized?')),
                ('key_phc_interventions_set', models.BooleanField(default=False, verbose_name='Have the key PHC interventions been set?')),
            ],
        ),
        migrations.CreateModel(
            name='Step4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensarization', models.BooleanField(default=False, verbose_name='Has Dispensarization (health status profiling) taken place ?')),
                ('multi_stakeholder_engagement', models.BooleanField(default=False, verbose_name='Has Multi-stakeholder engagement taken place ?')),
                ('mdt_roving_healthcare_provision', models.BooleanField(default=False, verbose_name='Has MDT roving healthcare provision taken place ?')),
                ('support_supervision_and_mentorships', models.BooleanField(default=False, verbose_name='Has Support supervision & mentorships taken place ?')),
                ('monitoring_and_evaluation', models.BooleanField(default=False, verbose_name='Has Monitoring and Evaluation, Learning & scale taken place ?')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='subcounty',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
    ]
