# Generated by Django 4.2.5 on 2023-09-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0013_step1_step2_step3_step4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='step1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phc.step1'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='step2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phc.step2'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='step3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phc.step3'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='step4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phc.step4'),
        ),
    ]
