# Generated by Django 4.2.5 on 2023-09-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0014_subcounty_step1_subcounty_step2_subcounty_step3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounty',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='step4',
        ),
        migrations.AddField(
            model_name='subcounty',
            name='chmt_meeting',
            field=models.BooleanField(default=False, verbose_name='Has CHMT meeting taken place?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='chu_functionality_assessments',
            field=models.BooleanField(default=False, verbose_name='Have the CHU functionality assessments taken place?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='client_exit_surveys',
            field=models.BooleanField(default=False, verbose_name='Have client exit surveys taken place?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='customised_performance_indicators',
            field=models.BooleanField(default=False, verbose_name='Have the performance indicators been customized (Step 3)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='dispensarization',
            field=models.BooleanField(default=False, verbose_name='Dispensarization (health status profiling) (Step 4)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='health_facility_assessments',
            field=models.BooleanField(default=False, verbose_name='Have Health Facility assessments taken place – using the 6 building blocks?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='m_e_learning_scale',
            field=models.BooleanField(default=False, verbose_name='M&E, Learning & scale (Step 4)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='mapping_hubs_spokes',
            field=models.BooleanField(default=False, verbose_name='Has the mapping of the hubs and spokes taken place (Step 3)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='mdt_roving_healthcare_provision',
            field=models.BooleanField(default=False, verbose_name='MDT roving healthcare provision (Step 4)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='multi_stakeholder_engagement',
            field=models.BooleanField(default=False, verbose_name='Multi-stakeholder engagement (Step 4)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='schmt_hf_staff_meeting',
            field=models.BooleanField(default=False, verbose_name='Has the SCHMT & HF staff meeting taken place?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='set_phc_interventions',
            field=models.BooleanField(default=False, verbose_name='Have the key PHC interventions been set (Step 3)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='support_supervision_mentorships',
            field=models.BooleanField(default=False, verbose_name='Support supervision & mentorships (Step 4)?'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='training_mdt',
            field=models.BooleanField(default=False, verbose_name='Has the training of multi-disciplinary teams (MDTs) taken place (Step 3)?'),
        ),
        migrations.DeleteModel(
            name='Step1',
        ),
        migrations.DeleteModel(
            name='Step2',
        ),
        migrations.DeleteModel(
            name='Step3',
        ),
        migrations.DeleteModel(
            name='Step4',
        ),
    ]
