# Generated by Django 4.2.5 on 2023-09-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0015_remove_subcounty_step1_remove_subcounty_step2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='stage1',
            field=models.BooleanField(default=False, verbose_name='Stage 1'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='stage2',
            field=models.BooleanField(default=False, verbose_name='Stage 2'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='stage3',
            field=models.BooleanField(default=False, verbose_name='Stage 3'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='stage4',
            field=models.BooleanField(default=False, verbose_name='Stage 4'),
        ),
    ]
