# Generated by Django 4.2.5 on 2023-09-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0016_subcounty_stage1_subcounty_stage2_subcounty_stage3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='progress',
            field=models.FloatField(default=0.0, verbose_name='Progress (%)'),
        ),
    ]
