# Generated by Django 4.2.5 on 2023-09-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0017_subcounty_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='progress',
            field=models.FloatField(default=0.0, verbose_name='Progress (%)'),
        ),
    ]
