# Generated by Django 4.2.5 on 2023-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0018_county_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounty',
            name='chmt_meeting',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='chu_functionality_assessments',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='client_exit_surveys',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='customised_performance_indicators',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='dispensarization',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='health_facility_assessments',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='m_e_learning_scale',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='mapping_hubs_spokes',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='mdt_roving_healthcare_provision',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='multi_stakeholder_engagement',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='schmt_hf_staff_meeting',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='set_phc_interventions',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='stage1',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='stage2',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='stage3',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='stage4',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='support_supervision_mentorships',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='training_mdt',
        ),
        migrations.AddField(
            model_name='subcounty',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_process', 'In Process'), ('fully_established', 'Fully Established')], default='not_started', max_length=20),
        ),
    ]
