# Generated by Django 4.2.5 on 2023-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0022_alter_subcounty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcounty',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Fully Established')], default=0),
        ),
    ]
