# Generated by Django 4.2.5 on 2023-09-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0023_alter_subcounty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='fully_established',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='county',
            name='in_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='county',
            name='not_started',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='county',
            name='partner_support',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
