# Generated by Django 4.2.5 on 2023-09-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0027_alter_county_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='in_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
