# Generated by Django 4.2.5 on 2023-09-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phc', '0028_alter_county_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='ongoing',
            field=models.FloatField(default=0.0, verbose_name='started (%)'),
        ),
    ]
